server:
  port: 8080

spring:
  application:
    name: gamenews

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    info:
      enabled: true
  server:
    port: ${MANAGEMENT_PORT:8081}

# CORS 설정을 위해 application.yml에 추가
cors:
  allowed-origins: ${ALLOWED_ORIGIN}, http://localhost:3000
